/* Twist.h
 * MSG file auto generated by "Rutgers avr_bridge"
 */
#ifndef TWIST_H_
#define TWIST_H_
#include "avr_ros/Msg.h"
#include "avr_ros/vector.h"
#include "avr_ros/ros_string.h"
#include "avr_ros/ros_float64.h"
#include "avr_ros/Vector3.h"
#include "avr_ros/Vector3.h"
namespace geometry_msgs {
	class Twist : public ros::Msg {
	public:
		virtual ros::MsgSz bytes();
		virtual ros::MsgSz serialize(uint8_t *out_buffer);
		virtual ros::MsgSz deserialize(uint8_t *data);
		geometry_msgs::Vector3 linear;
		geometry_msgs::Vector3 angular;
	}; /* class Twist */
} /* namespace geometry_msgs */
#endif /* TWIST_H_ */
