/* Vector3.h
 * MSG file auto generated by "Rutgers avr_bridge"
 */
#ifndef VECTOR3_H_
#define VECTOR3_H_
#include "avr_ros/Msg.h"
#include "avr_ros/vector.h"
#include "avr_ros/ros_string.h"
#include "avr_ros/ros_float64.h"
namespace geometry_msgs {
	class Vector3 : public ros::Msg {
	public:
		virtual ros::MsgSz bytes();
		virtual ros::MsgSz serialize(uint8_t *out_buffer);
		virtual ros::MsgSz deserialize(uint8_t *data);
		ros::float64 x;
		ros::float64 y;
		ros::float64 z;
	}; /* class Vector3 */
} /* namespace geometry_msgs */
#endif /* VECTOR3_H_ */
