/* ChameleonSense.h
 * MSG file auto generated by "Rutgers avr_bridge"
 */
#ifndef CHAMELEONSENSE_H_
#define CHAMELEONSENSE_H_
#include "avr_ros/Msg.h"
#include "avr_ros/vector.h"
#include "avr_ros/ros_string.h"
#include "avr_ros/ros_float64.h"
namespace chameleon_msgs {
	class ChameleonSense : public ros::Msg {
	public:
		virtual ros::MsgSz bytes();
		virtual ros::MsgSz serialize(uint8_t *out_buffer);
		virtual ros::MsgSz deserialize(uint8_t *data);
		float travel_left;
		float travel_right;
		float speed_left;
		float speed_right;
		float pwm_left;
		float pwm_right;
		float voltage;
	}; /* class ChameleonSense */
} /* namespace chameleon_msgs */
#endif /* CHAMELEONSENSE_H_ */
